name: cub3d CI

on:
    push:
        branches:
            - "**"

jobs:
    check:
        runs-on: ubuntu-24.04
        steps:
        - uses: actions/checkout@v4
        - name: Install X11 dependencies
          run: |
              sudo apt-get update
              sudo apt-get install -y libxext-dev libbsd-dev xvfb
        - name: norm
          run: |
              pip install norminette==3.3.55
              norminette srcs/* includes/*
        - name: make
          run: make
        - name: valgrind
          run: |
              sudo apt install valgrind
              xvfb-run -a valgrind --leak-check=full --show-leak-kinds=all --error-exitcode=1 ./cub3d maps/test.cub
        - name: clean_up
          run: make fclean
