name: cub3d CI

on:
    push:
        branches:
            - "**"

jobs:
    check:
        runs-on: ubuntu-24.04
        steps:
        - uses: actions/checkout@v4
        - name: Install X11 dependencies
          run: |
              sudo apt-get update
              sudo apt-get install -y libxext-dev libbsd-dev
        - name: norm
          run: |
              pip install norminette==3.3.55
              norminette srcs/ includes/
        - name: make
          run: make
        - name: clean_up
          run: make fclean
